### ISSUE TITLE
能否提供下运行的完整文档，包括配置文件，谢谢。

### ISSUE THREAD

**Issue by lupming** [PeyShine/Demo.MicroServer#1]
能否提供下运行的完整文档，包括配置文件，谢谢。

**Comment by PeyShine** [comment]
可以，后面整理下再发出来

**Comment by PeyShine** [comment]
> 能否提供下运行的完整文档，包括配置文件，谢谢。

可以，后面整理下再发出来

**Comment by PeyShine** [comment]
> 能否提供下运行的完整文档，包括配置文件，谢谢。

配置文档已出，可以看下是否能解决你的疑惑
http://liuthing.com/2020/07/06/demomicroserver-use/
