### ISSUE TITLE
有个ExceptionLess的问题请教

### ISSUE THREAD

**Issue by lhl102401** [PeyShine/Demo.MicroServer#2]
您好，我正在研究在k8s中部署ExceptionLess，git中给出的sh脚本非常复杂，需要安装很多的插件、配置，其实我已经单独安装了Redis和Elasticsearch ，我只保留了sh中helm的部分，传递了Redis和Elasticsearch 的IP，k8s成功部署了这些容器，但是内部的服务都没有启动成功。另一种方法使用hubdocker中的ExceptionLess 镜像，虽然可以成功启动，但是无法实现注册，输入任何电子邮件账号，都提示已经注册过。想请教下您是如何在cenotos中部署ExceptionLess

**Comment by PeyShine** [comment]
> 您好，我正在研究在k8s中部署ExceptionLess，git中给出的sh脚本非常复杂，需要安装很多的插件、配置，其实我已经单独安装了Redis和Elasticsearch ，我只保留了sh中helm的部分，传递了Redis和Elasticsearch 的IP，k8s成功部署了这些容器，但是内部的服务都没有启动成功。另一种方法使用hubdocker中的ExceptionLess 镜像，虽然可以成功启动，但是无法实现注册，输入任何电子邮件账号，都提示已经注册过。想请教下您是如何在cenotos中部署ExceptionLess

有关Exceptionless的部署，可以参考博客园Edison Zhou的这篇文章[https://www.cnblogs.com/edisonchou/p/exceptionless_v5_deployment_introduction.html](url)

**Comment by lhl102401** [comment]
谢谢您的回复，我会继续尝试



李寰
国开在线教育科技有限公司研发中心
地址：北京海淀区复兴路75号
Email：lihuan@ouchn.edu.cn
 
发件人： Peyshine
发送时间： 2020-09-13 23:10
收件人： PeyShine/Demo.MicroServer
抄送： H; Author
主题： Re: [PeyShine/Demo.MicroServer] 有个ExceptionLess的问题请教 (#2)
您好，我正在研究在k8s中部署ExceptionLess，git中给出的sh脚本非常复杂，需要安装很多的插件、配置，其实我已经单独安装了Redis和Elasticsearch ，我只保留了sh中helm的部分，传递了Redis和Elasticsearch 的IP，k8s成功部署了这些容器，但是内部的服务都没有启动成功。另一种方法使用hubdocker中的ExceptionLess 镜像，虽然可以成功启动，但是无法实现注册，输入任何电子邮件账号，都提示已经注册过。想请教下您是如何在cenotos中部署ExceptionLess
有关Exceptionless的部署，可以参考博客园Edison Zhou的这篇文章https://www.cnblogs.com/edisonchou/p/exceptionless_v5_deployment_introduction.html
